language: java

install:
  - git clone --depth=50 --branch=master https://github.com/cleberramiresmachado/tpack.git cleberramiresmachado/tpack
  - cd cleberramiresmachado/tpack
  - git checkout -qf $TRAVIS_COMMIT
  - cp scripts/settings.xml $HOME/.m2/settings.xml

services:
    - docker

jdk:
  - openjdk11

script: 
  - mvn pmd:pmd
  - mvn test
  - mvn clean package
  - docker-compose up -d

after_script:
notifications:
  recipients:
    - cleber.ramires.machado@gmail.com